name: Deploy

on:
  push:
    branches:
      - master
jobs: 
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        # Build
        - name: Run npm
          run: npm i
        - name: Run CI
          run: npm ci
        - name: Run build
          run: npm run build
        
        #Copy
        - name: Copy single file to remote
          uses: garygrossgarten/github-action-scp@release
          with:
            local: build
            remote: test
            host: ${{ secrets.HOST }}
            privateKey  : ${{ secrets.SSH_KEY }}
            username: ${{ secrets.USERNAME }}
            passphrase: ${{ secrets.PASSPHRASE }}
        # Deploy  
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            passphrase: ${{ secrets.PASSPHRASE }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.PORT }}
            script: |
                cd /var/www/polova.fun/frontend/
                pm2 stop next
                pm2 start npm --name "next" -- start
                git pull
                yarn install
                    
